
export const predefinedItems: { [key: string]: { label: string; weight: number } } = {
    shoes: { label: "احذية (0.60 كجم)", weight: 0.60 },
    light_accessories: { label: "اكسسوارات خفيفة (0.03 كجم)", weight: 0.03 },
    mug: { label: "اكواب(مق) (0.25 كجم)", weight: 0.25 },
    pajamas: { label: "بجامة قطعتين (0.30 كجم)", weight: 0.30 },
    antiques: { label: "تحف (0.30 كجم)", weight: 0.30 },
    tshirt: { label: "تيشرت (0.20 كجم)", weight: 0.20 },
    jacket: { label: "جاكيت (0.80 كجم)", weight: 0.80 },
    socks: { label: "جوارب (0.02 كجم)", weight: 0.02 },
    rings_chains: { label: "خواتم وسلاسل وحدايد (0.03 كجم)", weight: 0.03 },
    trousers: { label: "سروال (0.50 كجم)", weight: 0.50 },
    jeans: { label: "سروال جينز (0.60 كجم)", weight: 0.60 },
    slippers: { label: "شبشب منزل (0.20 كجم)", weight: 0.20 },
    abaya: { label: "عباية (0.60 كجم)", weight: 0.60 },
    bed_cover: { label: "غطاء سرير (0.80 كجم)", weight: 0.80 },
    dresses: { label: "فساتين (0.50 كجم)", weight: 0.50 },
    evening_dresses: { label: "فساتين سهرة خفيفة (0.30 كجم)", weight: 0.30 },
    silicone_molds: { label: "قوالب سيليكون (0.07 كجم)", weight: 0.07 },
    phone_cases: { label: "كفرات تلفون (0.04 كجم)", weight: 0.04 },
    lingerie: { label: "لانجري وملابس داخلية (0.10 كجم)", weight: 0.10 },
    winter_top: { label: "لباس علوي شتوي (0.40 كجم)", weight: 0.40 },
    sportswear: { label: "لبس رياضي قطعتين (0.50 كجم)", weight: 0.50 },
    makeup: { label: "ميك اب (0.15 كجم)", weight: 0.15 },
};
