// This file is generated by Gemini.

'use server';

/**
 * @fileOverview وكيل ذكاء اصطناعي يقترح عناصر قائمة أو إضافات ذات صلة بناءً على الطلب الحالي.
 *
 * - suggestMenuItems - دالة تتعامل مع عملية اقتراح عناصر القائمة.
 * - SuggestMenuItemsInput - نوع الإدخال لدالة suggestMenuItems.
 * - SuggestMenuItemsOutput - نوع الإرجاع لدالة suggestMenuItems.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestMenuItemsInputSchema = z.object({
  currentOrder: z
    .string()
    .describe('الطلب الحالي كسلسلة نصية مفصولة بفواصل لعناصر القائمة.'),
  menu: z.string().describe('القائمة الكاملة كسلسلة نصية مفصولة بفواصل لعناصر القائمة مع الأسعار.'),
});
export type SuggestMenuItemsInput = z.infer<typeof SuggestMenuItemsInputSchema>;

const SuggestMenuItemsOutputSchema = z.object({
  suggestions: z
    .string()
    .describe('عناصر القائمة أو الإضافات المقترحة بناءً على الطلب الحالي.'),
});
export type SuggestMenuItemsOutput = z.infer<typeof SuggestMenuItemsOutputSchema>;

export async function suggestMenuItems(input: SuggestMenuItemsInput): Promise<SuggestMenuItemsOutput> {
  return suggestMenuItemsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestMenuItemsPrompt',
  input: {schema: SuggestMenuItemsInputSchema},
  output: {schema: SuggestMenuItemsOutputSchema},
  prompt: `أنت مساعد ذكاء اصطناعي مفيد يقترح عناصر قائمة أو إضافات ذات صلة بناءً على الطلب الحالي وقائمة المطعم.

الطلب الحالي: {{{currentOrder}}}
القائمة: {{{menu}}}

الاقتراحات:`,
});

const suggestMenuItemsFlow = ai.defineFlow(
  {
    name: 'suggestMenuItemsFlow',
    inputSchema: SuggestMenuItemsInputSchema,
    outputSchema: SuggestMenuItemsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
