// This file is generated by Gemini.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "studio-2340324570-4ec90",
  "appId": "1:800042604350:web:f0deea6cba519453b8fe6f",
  "storageBucket": "studio-2340324570-4ec90.firebasestorage.app",
  "apiKey": "AIzaSyDuhOHjtNzpbI5HGMIe1F25c-6S0Jz6FCY",
  "authDomain": "studio-2340324570-4ec90.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "800042604350"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
